### ISSUE TITLE
Blocked 

### ISSUE THREAD

**Issue by gitbucket-crypto** [markcellus/youtube-video-js#539]
I tryed run the examples folders they return this erros I'm at Windows. How to solve not big experience  on nodejs modules

module from “http://localhost:3000/youtube-video-js/dist/youtube-video.js” was blocked because of a disallowed

**Comment by markcellus** [comment]
Hey, thanks for filing issue! Before I can look more into this for you, I'll need a few more details about your environment:

1. Which Windows version?
2. What browser and version?
3. What version of this package?

**Comment by markcellus** [comment]
Closing for now due to no response. But feel free to reopen if you can provide more details. Thanks
